name: Account Services CICD

on:
    push:
      branches:
        - main
      paths:
        - .github/workflows/build-account-services.yaml
        - src/PlantBasedPizza.Account/**
        - src/shared/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-dev:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/cdk-deploy-base.yaml@main
    concurrency:
      group: account-dev-deploy
      cancel-in-progress: false
    with:
      cdk-folder: "src/PlantBasedPizza.Account/infra"
      environment: "dev"
    secrets:
      deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}
      dd-api-key: ${{secrets.DD_API_KEY}}